excerpt_separator: <!--more-->

baseurl: ""
url: "http://nathan-mccallum.com"
timezone: Australia/Brisbane
encoding: utf-8
lang: en
rss: RSS

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-youtube

include:
  - CNAME
  - robots.txt
  - humans.txt
