baseurl: ""
url: "http://nathan-mccallum.com"
timezone: Australia/Brisbane
encoding: utf-8
lang: en
rss: RSS
title: Nathan McCallum

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-youtube

include:
  - CNAME
  - robots.txt
  - humans.txt

exclude:
  - docker-compose.yml
  - Dockerfile
  - package.json
  - yarn.lock
  - img/

jekyll_compose:
  default_front_matter:
    posts:
      description:
      tags:
      permalink:
