# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nathan's Public Domicile

author:
  name: Nathan McCallum
  email: nathan@1vas.me

description: >-
  Hi! I'm a web developer who specializes in Ruby, Rails, Node.js & frontend technologies such as
  React. In my spare time I like to play guitar and experiment with electronic music production.
#I'm available for consulting work - please reach out to me via email!

baseurl: ""
url: "http://nathan-mccallum.com"
timezone: Australia/Brisbane
encoding: utf-8
lang: en
rss: RSS

header_pages:
  - about.md
  - projects.md
  - resume.md

minima:
  skin: solarized-dark
  social_links:
    github: 1vasari
    youtube: 1vasari
    instagram: 1vasari
    linkedin: 1vasari

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-sitemap
include:
  - CNAME
  - robots.txt
  - humans.txt

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
