version: '3'

volumes:
  node_modules:

services:
  site:
    build: .
    command: bundle exec jekyll serve --drafts --host '0.0.0.0'
    volumes:
      - '.:/usr/src/site'
      - 'node_modules:/usr/src/site/node_modules'
    ports:
      - '4000:4000'
    expose:
      - 4000
