version: '3'

volumes:
  node_modules:

services:
  web:
    build: .
    command: bundle exec jekyll serve --drafts --host '0.0.0.0' --port 3000 --force_polling
    volumes:
      - '.:/usr/src/site'
      - 'node_modules:/usr/src/site/node_modules'
    ports:
      - '3000:3000'
    expose:
      - 3000
